# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contents', models.TextField(blank=True)),
            ],
        ),
    ]
