# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='contents',
            new_name='content',
        ),
    ]
